name: Module Unit Testing
on:
  workflow_dispatch:
#  pull_request:
#    branches:
#      - main
#      - 'Feature**'
  push:
    branches:
      - main
      - 'Feature**'
      - 'feature**'
      - 'fix**'
      - 'Fix**'

permissions:
  id-token: write
  contents: read

jobs:
  module-testing-job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login using OIDC'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Actions Checkout v3'
        uses: actions/checkout@v3
      - name: 'Setup Go'
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: 'Setup Terraform v1.3.7'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
          terraform_wrapper: false
      - name: 'Download Go Modules'
        working-directory: test
        run: go mod init github.com/cloudreach/ul-azure-network-tf-module/test ; go mod tidy
      - name: 'Run Terratests'
        working-directory: test
        run: go test ./... -v -timeout 30m
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

        #run: go test ./... -v -timeout 30m